app: devices-api
service: devices-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:675174937919:table/devices"

package:
  patterns:
    - '!./**'
    - ./bin/**
  include:
    - ./bin/devices
  individually: true
  exclude:
    - ./**

functions:
  insertDevices:
    handler: bin/InsertDevice
    events:
      - http:
          path: /api/insertDevice
          method: post
          cors: true
    package:
      include:
         - ./bin/InsertDevice 
  getDevices:
    handler: bin/GetDevice
    events:
      - http:
          path: /api/GetDevice
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                id: true
    package:
      include:
         - ./bin/GetDevice

Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: devices
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: deviceModel
          AttributeType: S
        - AttributeName: name
          AttributeType: S
        - AttributeName: note
          AttributeType: S
        - AttributeName: serial
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST