# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!


app: devices-api
service: devices-api


# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [ devices ]


provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:675174937919:table/devices"

package:
  patterns:
    - '!./**'
    - ./bin/**
  include:
    - ./bin/devices
  individually: true
  exclude:
    - ./**

functions:
  insertDevices:
    handler: bin/InsertDevice
    events:
      - http:
          path: /api/insertDevice
          method: post
          cors: true
    package:
      include:
         - ./bin/InsertDevice 
  getDevices:
    handler: bin/GetDevice
    events:
      - http:
          path: /api/GetDevice
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                id: true
    package:
      include:
         - ./bin/GetDevice

        
Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: devices
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: deviceModel
          AttributeType: S
        - AttributeName: name
          AttributeType: S
        - AttributeName: note
          AttributeType: S
        - AttributeName: serial
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST